language: go

notificaitons:
  email:
    recipients: bluesuncorp01@gmail.com
    on_success: change
    on_failure: always

before_script:
- go get gopkg.in/check.v1

go:
  - 1.2
  - 1.3
  - 1.4
  - tip